#!/usr/bin/python3

"""
A little importer script to import the agon VDP to this platformio project.
"""

import argparse
import re
import shutil
import textwrap

from pathlib import Path


FUNCTION_START = re.compile(r"^(\S+) .+{")


def import_vdp(source: Path):
    if not source.is_dir():
        raise FileNotFoundError(source)

    for header in source.glob("*.h"):
        shutil.copyfile(header, Path("include") / header.name)

    with open(source / "video.ino") as input, open("src/main.cpp", "w") as output:
         for line in input:
            if line.startswith("#define VERSION"):
                output.write('#include "arduino_compat.h"\n')
            output.write(line)

    with open("src/main.cpp") as input, open("include/arduino_compat.h", "w") as output:
        output.write(textwrap.dedent('''
            // Generated by import script...
            #include <WiFi.h>
            #define ARDUINO 1

        '''))
        for line in input:
            matched = False
            if mo := FUNCTION_START.match(line):
                if mo.group(1) in ["void", "Point", "bool", "char", "word"]:
                    output.write(line.strip()[:-1].strip() + ";\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("vdp_dir", type=Path)
    args = parser.parse_args()
    import_vdp(args.vdp_dir)

if __name__ == "__main__":
    main()
